owner: massalabs
repo: website-status

sites:
  - name: Current Testnet
    url: https://test.massa.net/api/v2
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "jsonrpc": "2.0", "method": "get_cliques", "params": [], "id": 0 }'
  - name: Massa 
    url: https://massa.net/
  - name: InnoNet v18
    url: https://inno.massa.net/test18
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "jsonrpc": "2.0", "method": "get_cliques", "params": [], "id": 0 }'
  - name: InnoNet v17
    url: https://inno.massa.net/test17
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "jsonrpc": "2.0", "method": "get_cliques", "params": [], "id": 0 }'
  - name: InnoNet v13 with U32
    url: https://inno.massa.net/test13
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "jsonrpc": "2.0", "method": "get_cliques", "params": [], "id": 0 }'


status-website:
  baseUrl: /website-status
  logoUrl: https://avatars.githubusercontent.com/u/92152619
  name: Massa status
  introTitle: "Massa status website."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Massa
      href: https://massa.net/
